title: Python Best Practices
tagline: Learn the best practices for coding in Python
description: >-
  This course covers the best Python coding practices every developer should
  know.
template:
  name: python-best-practices-course
  repo: python-best-practices-v2-template
  description: Description
#################################################################
#
#
#################################################################
before:
  - type: updateBranchProtection
    store:
      repository_name: '{{ payload.repository.name }}'
      repository_url: '{{ payload.repository.html_url }}'
      repository_owner: '{{ payload.repository.owner.login }}'
      repository_default_branch: '{{ payload.repository.default_branch }}'
  #   Create the first issue  
  - type: createIssue
    title: Set up a Python Project
    body: 00_welcome.md
    store:
      first_issue_num: '{{result.data.number}}'
      first_issue_url: '{{result.data.html_url}}'
  # Respond in first issue with first activity
  - type: respond
    with: 01_add-LICENSE.md
    issue: '{{store.first_issue_num}}'
    data:
      quicklink: '{{store.repository_url}}/new/main?filename=LICENSE'
# end before

steps:
  #############################################################
  # Step 1
  # - User commits to head branch of first_pull
  # - App checks if LICENSE exists at top-level
  # - App responds, asks user to commit LICENSE
  #############################################################
  - title: Add a LICENSE file.
    description: Use GitHub to add a LICENSE file from a template.
    event: pull_request.opened
    link: '{{store.first_issue_url}}'
    actions:
    ###########################################################
    # Validate the filepath for the expected file
    ###########################################################
      # get tree
      - type: getTree
        action_id: isInTree
        recursive: true
        sha: '%payload.pull_request.head.sha%'
        # doing this here because its the first action
        store:
          first_pull_url: '{{payload.pull_request.html_url}}'
          first_pull_num: '{{payload.pull_request.number}}'
          first_pull_headref: '{{payload.pull_request.head.ref}}'
      # Create README.md
      - type: createFile
        filename: t-README-template.md
        branch: '%payload.pull_request.head.ref%'
        new_name: README.md
        message: Created a README.md from a template.
      # check for a file in a tree
      - type: gate
        left: '%actions.isInTree.data.tree%'
        operator: includes
        right: 'path:LICENSE'
        else:
          # help user with proper file name or location
          - type: respond
            with: e-wrong-file-location.md
            data:
              haveFile: ''
              needFile: LICENSE
              editLink: >-
                {{store.repository_url}}/new/{{store.first_pull_headref}}?filename=LICENSE
              fileName: LICENSE
          - type: respond
            with: 02_add-gitignore.md
            data:
               quicklink: >-
                  %store.repository_url%/new/%payload.pull_request.head.ref%?filename=.gitignore
        # End filepath verification
      - type: respond
        with: 02_add-gitignore.md
        data:
          quicklink: >-
            %store.repository_url%/new/%payload.pull_request.head.ref%?filename=.gitignore
  #############################################################
  # Step 2: Add a Python .gitignore file.
  # - User commits to head branch
  # - App checks if .gitignore exists at top-level
  # - App responds, asks user to merge PR
  # ToDo
  # - Check that it is the right file for Python?
  #############################################################
  - title: Add a .gitignore file.
    description: Use GitHub to add a .gitignore file from a template.
    event: pull_request.synchronize
    link: '{{ store.first_pull_url }}'
    actions:
    ###########################################################
    # Validate the filepath for the expected file
    ###########################################################
      # get tree
      - type: getTree
        action_id: isInTree
        recursive: true
        sha: '%payload.pull_request.head.sha%'
      # check for a file in a tree
      - type: gate
        left: '%actions.isInTree.data.tree%'
        operator: includes
        right: 'path:.gitignore'
        else:
          # if file isn't where expected find true location
          - type: findInTree
            path: .gitignore
            tree: '%actions.isInTree.data.tree%'
            action_id: fileLocation
          # help user with proper file location
          - type: respond
            with: e-wrong-file-location.md
            issue: '{{store.first_pull_num}}'
            data:
              haveFile: '%actions.fileLocation.path%'
              needFile: .gitignore
              editLink: >-
                {{store.repository_url}}/new/{{store.first_pull_headref}}?filename=.gitignore
              fileName: .gitignore
          # Approve PR 
          - type: createReview
            body: 03_added-README-merge.md
            event: APPROVE
            data:
              files_changed_tab: '%store.repository_url%/pull/2/files'
              readme_link: >-
                %store.repository_url%/blob/%payload.pull_request.head.ref%/README.md
        # End filepath verification
      
      # Approve PR 
      - type: createReview
        body: 03_added-README-merge.md
        event: APPROVE
        data:
          files_changed_tab: '%store.repository_url%/pull/2/files'
          readme_link: >-
            %store.repository_url%/blob/%payload.pull_request.head.ref%/README.md

  #############################################################
  # Step 3: Merge PR
  # - User merges first PR
  # - App closes first issue
  # - App creates new issue
  # - App responds in closed PR with link to new issue for next
  #   step
  #############################################################
  - title: Merge the First Pull Request
    description: Merge the preliminary files to start the project
    event: pull_request.closed
    link: '{{ store.second_pull_url }}'
    actions:
      - type: respond
        with: d-check-a-value.md
        data:
          value: Creating content for the next step...
      # Create next issue
      - type: createIssue
        title: Add your Own Python Package
        body: 04_add-python-code.md
        store:
          second_issue_num: '{{result.data.number}}'
          second_issue_url: '{{result.data.html_url}}'
      # respond with link
      - type: respond
        with: go-to-next-issue.md
        data:
          quicklink: '{{store.second_issue_url}}'
      # Close first issue
      - type: closeIssue
        issue: '%store.first_issue_num%'
      # Respond with next activity
      - type: respond
        issue: "%store.second_issue_num%"
        with: 04_add-init-files.md
        data:
          quicklink1: '%store.repository_url%/new/main?filename=src/digit_reader/__init__.py%'
          quicklink2: '%store.repository_url%/new/main?filename=src/digit_reader/model/__init__.py%'

# The next step should look for pull_request.opened
  
  #############################################################
  # Step 4: Add __init__.py for planned packages/modules
  #
  #
  #
  #############################################################
  - title: Add __init__.py files to package.
    description: Create a working package directory by adding the magic python files
    event: pull_request.opened
    link: '{{ store.second_pull_url }}'
    actions:
    ###########################################################
    # Validate the filepath for the expected file
    ###########################################################
      # get tree
      - type: getTree
        action_id: isInTree
        recursive: true
        sha: '%payload.pull_request.head.sha%'
        store:
          second_pull_url: '{{payload.pull_request.html_url}}'
          second_pull_num: '{{payload.pull_request.number}}'
      # check for a file in a tree
      - type: gate
        left: '%actions.isInTree.data.tree%'
        operator: includes
        right: 'path:.gitignore'
        else:
          # if file isn't where expected find true location
          - type: findInTree
            path: src/digit_reader/__init__.py
            tree: '%actions.isInTree.data.tree%'
            action_id: fileLocation
          # help user with proper file location
          - type: respond
            with: e-wrong-file-location.md
            issue: '{{store.second_pull_num}}'
            data:
              haveFile: '%actions.fileLocation.path%'
              needFile: src/digit_reader/__init__.py
              editLink: >-
                %payload.repository.html_url%/edit/%payload.pull_request.head.ref%/%actions.fileLocation.path%
              fileName: src/digit_reader/__init__.py
        # End filepath verification

      # Probably should validate other file as well...
      - type: respond
        with: 05_add-python-module.md
        data:
          quicklink1: '%store.repository_url%/new/%payload.pull_request.head.ref%?filename=src/digit_reader/model/model.py%'

      
  #############################################################
  # Step 5: Add skeleton module code
  #
  #
  # 
  #############################################################
  - title: Add skeleton for python module code.
    description: Add the module file with basic outline of class and methods that will be needed
    event: pull_request.synchronize
    link: '{{ store.second_pull_url }}'
    actions:
    ###########################################################
    # Validate the filepath for the expected file
    ###########################################################
      # get tree
      - type: getTree
        action_id: isInTree
        recursive: true
        sha: '%payload.pull_request.head.sha%'
      # check for a file in a tree
      - type: gate
        left: '%actions.isInTree.data.tree%'
        operator: includes
        right: 'path:src/digit_reader/digit_reader.py'
        else:
          # if file isn't where expected find true location
          - type: findInTree
            path: src/digit_reader/digit_reader.py
            tree: '%actions.isInTree.data.tree%'
            action_id: fileLocation
          # help user with proper file location
          - type: respond
            with: e-wrong-file-location.md
            issue: '{{store.second_pull_num}}'
            data:
              haveFile: '%actions.fileLocation.path%'
              needFile: src/digit_reader/digit_reader.py
              editLink: >-
                %payload.repository.html_url%/edit/%payload.pull_request.head.ref%/%actions.fileLocation.path%
              fileName: src/digit_reader/digit_reader.py
        # End filepath verification
      # Probably should validate other file as well...
      - type: respond
        with: 06_add-docstrings.md

  #############################################################
  # Step 6: Add docstrings
  #############################################################
  - title: Add skeleton for python module code.
    description: Add the module file with basic outline of class and methods that will be needed
    event: pull_request.synchronize
    link: '{{ store.second_pull_url }}'
    actions:
      - type: respond
        with: 06-continue-to-merge.md
        data:
          quicklink1: '%store.repository_url%/new/%payload.pull_request.head.ref%'
      - type: createReview
        body: 03_added-README-merge.md
        event: APPROVE
          

  #############################################################
  # Step 7: Merge PR
  # - User merges second PR
  # - App closes second issue
  # - App creates new issue
  # - App responds in closed PR with link to new issue for next
  #   step
  #############################################################
  - title: Merge the Second Pull Request
    description: Merge the preliminary files to start the project
    event: pull_request.closed
    link: '{{store.first_issue_url}}'
    actions:
      - type: respond
        with: d-check-a-value.md
        data:
          value: Creating content for the next step...
      # Create next issue
      - type: createIssue
        title: Add Module Code tests and setup.py
        body: 08_introduce.md
        store:
          third_issue_num: '{{result.data.number}}'
          third_issue_url: '{{result.data.html_url}}'
      # respond with link
      - type: respond
        with: go-to-next-issue.md
        data:
          quicklink: '{{store.third_issue_url}}'
      # Close second issue
      - type: closeIssue
        issue: '%store.second_issue_num%'
      # Respond with next activity
     # - type: respond
     #   issue: "%store.third_issue_num%"
     #   with: 08-??.md

  #############################################################
  # Step: 8
  #############################################################

  #############################################################
  # Step: 9
  #############################################################

  #############################################################
  # Step: 10
  #############################################################

#############################################################
  # Step: 4
  #############################################################







  #############################################################
  # Below are older steps that may be useful to pull into the course above
  #############################################################

#   # Step 4: Add google-style comment blocks in formatting.py
#   - title: Add google-style comment blocks in formatting.py
#     description: NA
#     event: push
#     link: '{{ repoUrl }}/issues/2'
#     actions:
#       - type: getFileContents
#         action_id: formatting2Contents
#         filename: formatting.py
#       # Need to write a regex to check for comment blocks. Ideally we should write
#       # multiple gates for multiple comment types the user can add
#       # Refer to https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html 
#       # for google comment examples Currently, only one simple regex check is executed
#       # We need to write a regex that checks whether the file contains the solution we desire 
#       #(currently checks if file contains 'x = 5')
#       - type: gate
#         left: /x\s=\s5/g
#         operator: test
#         right: '%actions.formatting2Contents%'
#         else:
#           - type: respond
#             with: 02_bad-google-comment.md
#             issue: 2
#       - type: createIssue
#         title: Pip install and requirements.txt
#         body: 03_pip-and-venv.md
#         action_id: third_issue
#       - type: respond
#         with: 02_successful-push.md
#         issue: 2
#         data:
#           url: '%actions.third_issue.data.html_url%'
# # Step 5: Create dependencies in setup.py and use pip tools to create a requirements.txt
#   - title: >-
#       Create dependencies in setup.py and use pip tools to create a
#       requirements.txt
#     description: NA
#     event: push
#     link: '{{ repoUrl }}/issues/3'
#     actions:
#       - type: getFileContents
#         action_id: setup2Contents
#         filename: setup.py
#       # We need to write a regex that checks whether the file contains the solution we
#       # desire (currently checks if file contains 'a = 5')
#       - type: gate
#         left: /a\s=\s5/g
#         operator: test
#         right: '%actions.setup2Contents%'
#         else:
#           - type: respond
#             with: 03_bad-setup.md
#             issue: 3
#       - type: getFileContents
#         action_id: requirementsContents
#         filename: requirements.txt
#       # We need to write a regex that checks whether the file contains the solution we
#       # desire (currently checks if file contains 'numpy')
#       - type: gate
#         left: /numpy/g
#         operator: test
#         right: '%actions.requirementsContents%'
#         else:
#           - type: respond
#             with: 03_bad-requirements.md
#             issue: 3
#       - type: respond
#         with: 03_activate-venv.md
#         issue: 3
# # Step 6: Install/create/activate virtual environment and Pip install packages using requirements.txt
#   - title: >-
#       Install/create/activate virtual environment and Pip install packages using
#       requirements.txt
#     description: NA
#     event: issue_comment.created
#     link: '{{ repoUrl }}/issues/3'
#     actions:
#       # We need to write a regex that checks whether the comment contains the output we
#       # desire (currently checks if comment contains 'Output')
#       - type: gate
#         left: /Output/g
#         operator: test
#         right: '%payload.comment.body%'
#         else:
#           - type: respond
#             with: 03_bad-comment.md
#             issue: 3
#       - type: createIssue
#         title: Pytest
#         body: 04_pytest.md
#         action_id: fourth_issue
#       - type: respond
#         with: 03_successful-push.md
#         issue: 3
#         data:
#           url: '%actions.fourth_issue.data.html_url%'
#   # Step 7: Run existing tests in the repository
#   - title: Run an existing test
#     description: NA
#     event: issue_comment.created
#     link: '{{ repoUrl }}/issues/4'
#     actions:
#       # We need to write a regex that checks whether the comment contains the output we
#       # desire (currently checks if comment contains 'ERROR')
#       - type: gate
#         left: /ERROR/g
#         operator: test
#         right: '%payload.comment.body%'
#         else:
#           - type: respond
#             with: 04_bad-comment.md
#             issue: 3
#       - type: respond
#         with: 04_successful-push.md
#         issue: 4
#   # Step 8: Fix failing test in the repository
#   - title: Fix a failing test
#     description: >-
#       Commit the fix to the test in a new branch, create a pull request to merge
#       to fix pytest branch
#     event:
#       - pull_request
#       - check_suite.completed
#     link: '{{ repoUrl }}/issues/4'
#     actions:
#       - type: gate
#         left: '%payload.pull_request.title%'
#         operator: ===
#         right: Fix Pytest
#         else:
#           - type: respond
#             with: 04_bad-pull-request.md
#             issue: 1
#       - type: respond
#         with: 04_successful-pr.md
#         issue: 1
#       - type: gate
#         left: '%payload.check_suite.conclusion%'
#         operator: ===
#         right: success
#         else:
#           - type: respond
#             with: 04_bad-check-run.md
#             issue: 1
#       - type: respond
#         with: 04_successful-push.md
#         issue: 1
